name: sdtpro
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  exui: ^1.0.7
  flutter_colorpicker: ^1.1.0
  flutter_riverpod: ^3.0.0-dev.17
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.2.2
  intl: ^0.20.2
  image_picker: ^1.2.0
  image_gallery_saver_plus: ^4.0.1
  material_symbols_icons: ^4.2858.1
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^11.3.1
  printing: ^5.14.2
  riverpod_annotation: ^3.0.0-dev.17
  screenshot: ^3.0.0
  share_plus: ^11.1.0
  sqflite: ^2.4.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  custom_lint:
  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/db/
    - assets/logos/
    - assets/fonts/
  
  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide-Regular.ttf
    - family: Barriecito
      fonts:
        - asset: assets/fonts/Barriecito-Regular.ttf
    - family: Bitcount Grid Double
      fonts:
        - asset: assets/fonts/BitcountGridDouble-Regular.ttf
    - family: Cabin Sketch
      fonts:
        - asset: assets/fonts/CabinSketch-Regular.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf
    - family: DynaPuff
      fonts:
        - asset: assets/fonts/DynaPuff-Regular.ttf
    - family: Fuzzy Bubbles
      fonts:
        - asset: assets/fonts/FuzzyBubbles-Regular.ttf
    - family: Great Vibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf
    - family: Iceberg
      fonts:
        - asset: assets/fonts/Iceberg-Regular.ttf
    - family: Kablammo
      fonts:
        - asset: assets/fonts/Kablammo-Regular-VariableFont_MORF.ttf
    - family: Leckerli One
      fonts:
        - asset: assets/fonts/LeckerliOne-Regular.ttf
    - family: Limelight
      fonts:
        - asset: assets/fonts/Limelight-Regular.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Monoton
      fonts:
        - asset: assets/fonts/Monoton-Regular.ttf
    - family: Pirata One
      fonts:
        - asset: assets/fonts/PirataOne-Regular.ttf
    - family: Quintessential
      fonts:
        - asset: assets/fonts/Quintessential-Regular.ttf
    - family: Racing Sans One
      fonts:
        - asset: assets/fonts/RacingSansOne-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Rubik Glitch
      fonts:
        - asset: assets/fonts/RubikGlitch-Regular.ttf
    - family: Tiny5
      fonts:
        - asset: assets/fonts/Tiny5-Regular.ttf

flutter_intl:
  enabled: true
  arb_dir: l10n
  output_dir: lib/l10n
  class_name: AppLocalizations
  synthetic_package: true

better_imports:
  ignore_files:
    - app_localizations
    - app_localizations_de
    - app_localizations_en