name: sdtpro
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  exui: ^1.0.7
  flutter_riverpod: ^3.0.0-dev.17
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.3.1
  http: ^1.2.2
  intl: ^0.20.2
  image_picker: ^1.2.0
  image_gallery_saver_plus: ^4.0.1
  material_symbols_icons: ^4.2858.1
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^11.3.1
  printing: ^5.14.2
  riverpod_annotation: ^3.0.0-dev.17
  screenshot: ^3.0.0
  share_plus: ^11.1.0
  sqflite: ^2.4.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  custom_lint:
  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/db/ # Existing asset
    - assets/logos/ # Add this line for the new logos

flutter_intl:
  enabled: true
  arb_dir: l10n
  output_dir: lib/l10n
  class_name: AppLocalizations
  synthetic_package: true

better_imports:
  ignore_files:
    - app_localizations
    - app_localizations_de
    - app_localizations_en